version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:

  build:
    commands:
      - mvn clean test -Dcucumber.options="--tags '@UITest and @Smoke'" -DexecutionPlatform="AWS_DEVICEFARM_CHROME"

  post_build:
    commands:
      - aws s3 cp . s3://233632-mohanraj-mathavan-bootcamp-results/devicefarm --recursive --exclude "*" --include "*.html"
